live:
  - name: Ethereum
    networks:
      - name: Goerli (Alchemy)
        chainid: 5
        id: goerli-alchemy
        host: https://eth-goerli.g.alchemy.com/v2/$WEB3_ALCHEMY_PROJECT_ID
        explorer: https://api-goerli.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: alchemy
